### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by zevisvei** [AppsForDesktop/Google-translate-desktop#1]
I saw that it says that the translation will also work offline, but when I open the software without internet, a white window comes up, what's more, I don't see an option to download languages for offline use
Another problem - when I try to log into my Google account, it tells me that the browser is not supported
Thank you

**Comment by AppsForDesktop** [comment]
> I saw that it says that the translation will also work offline, but when I open the software without internet, a white window comes up, what's more, I don't see an option to download languages for offline use Another problem - when I try to log into my Google account, it tells me that the browser is not supported Thank you

Thank you very much for bug report, we will look and try to fix the issues you specified.

**Comment by AppsForDesktop** [comment]
> I saw that it says that the translation will also work offline, but when I open the software without internet, a white window comes up, what's more, I don't see an option to download languages for offline use Another problem - when I try to log into my Google account, it tells me that the browser is not supported Thank you

Sorry but there was a mistake in description, This app will not work offline. We already corrected that mistake.
About "browser is not supported" error, it is because of underlying software that we use to drive Google translate desktop, the issue is there and the fix will be by the browser team, but it will be a little bit later.

**Comment by mhotjrubho** [comment]
Can you improve the offline option?
